name: Build and Push Docker Image to GHCR

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: conanslash@gmail.com
          password: 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


      - name: Build Docker image
        run: |
          docker build -t ghcr.io/conanslash/sample-nodes-app:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/conanslash/sample-nodes-app:latest
